// Define primitives first
const primitives = {
  "groww-primary": {
    colors: {
      black: { light: "#121212", dark: "#121212" },
      white: { light: "#ffffff", dark: "#ffffff" },
      gray900: { light: "#44475b", dark: "#f8f8f8" },
      gray800: { light: "#696c7c", dark: "#d1d1d1" },
      gray700: { light: "#7c7e8c", dark: "#b8b8b8" },
      gray600: { light: "#8f919d", dark: "#a0a0a0" },
      gray500: { light: "#a1a3ad", dark: "#888888" },
      gray400: { light: "#b0b2ba", dark: "#717171" },
      gray300: { light: "#c7c8ce", dark: "#595959" },
      gray200: { light: "#dddee1", dark: "#414141" },
      gray150: { light: "#e9e9eb", dark: "#2e2e2e" },
      gray100: { light: "#f0f0f2", dark: "#252525" },
      gray50: { light: "#f8f8f8", dark: "#1b1b1b" },
      green500: { light: "#04B488", dark: "#04B488" },
      green300: { light: "#66e3c4", dark: "#0b5e49" },
      green100: { light: "#E9FAF3", dark: "#0F251D" },
      purple500: { light: "#5367ff", dark: "#98a4ff" },
      purple300: { light: "#84a4ff", dark: "#323c89" },
      purple100: { light: "#eef0ff", dark: "#181a2a" },
      yellow500: { light: "#ffb61b", dark: "#e7a61a" },
      yellow100: { light: "#fff5e0", dark: "#46391d" },
      red500: { light: "#ED5533", dark: "#FF5E3B" },
      red100: { light: "#fae9e5", dark: "#411d16" },
      overlay00: { light: "rgba(18, 18, 18, 0)", dark: "rgba(18, 18, 18, 0)" },
      overlay30: { light: "rgba(18, 18, 18, 0.3)", dark: "rgba(18, 18, 18, 0.3)" },
      overlay70: { light: "rgba(18, 18, 18, 0.7)", dark: "rgba(18, 18, 18, 0.7)" },
      // Yellow
      yellow1: { light: "#FEFDFB", dark: "#14120D" },
      yellow2: { light: "#FFF7DE", dark: "#291F0E" },
      yellow3: { light: "#FFF1C3", dark: "#2D210D" },
      yellow4: { light: "#FFE7AA", dark: "#3D2800" },
      yellow5: { light: "#FFDC8B", dark: "#4A3200" },
      yellow6: { light: "#FFCD65", dark: "#573F12" },
      yellow7: { light: "#F5BC57", dark: "#6C5121" },
      yellow8: { light: "#E4A417", dark: "#89682C" },
      yellow9: { light: "#E7A71E", dark: "#E7A71E" },
      yellow10: { light: "#DB9C00", dark: "#DB9C00" },
      yellow11: { light: "#A16B00", dark: "#F5BC56" },
      yellow12: { light: "#4A3819", dark: "#FAE5C3" },
      // Red
      red1: { light: "#FFFCFB", dark: "#17100E" },
      red2: { light: "#FFF1ED", dark: "#2C1711" },
      red3: { light: "#FFEBE6", dark: "#391810" },
      red4: { light: "#FFDACF", dark: "#4F1509" },
      red5: { light: "#FFCBBC", dark: "#5F1D0E" },
      red6: { light: "#FFBBAB", dark: "#6F2A1A" },
      red7: { light: "#F7A895", dark: "#883A29" },
      red8: { light: "#EE8E78", dark: "#AF4B35" },
      red9: { light: "#ED5533", dark: "#FF5E3B" },
      red10: { light: "#DF4622", dark: "#F1512E" },
      red11: { light: "#D23A15", dark: "#FF9479" },
      red12: { light: "#5B291D", dark: "#FFD5CA" },
      // Green
      green1: { light: "#FAFEFC", dark: "#0C1411" },
      green2: { light: "#E9FAF3", dark: "#0F251D" },
      green3: { light: "#E0F8EE", dark: "#0C2E22" },
      green4: { light: "#CDF3E3", dark: "#043C2B" },
      green5: { light: "#B7ECD6", dark: "#084936" },
      green6: { light: "#9CE2C6", dark: "#145742" },
      green7: { light: "#75D3B0", dark: "#1E6951" },
      green8: { light: "#24BF92", dark: "#227F62" },
      green9: { light: "#04B488", dark: "#04B488" },
      green10: { light: "#00A87D", dark: "#00A87D" },
      green11: { light: "#00825C", dark: "#46D5A7" },
      green12: { light: "#0D3D2E", dark: "#A7F2D4" },
      // Blue
      blue1: { light: "#FDFDFE", dark: "#0E111E" },
      blue2: { light: "#F2F5FF", dark: "#161D3A" },
      blue3: { light: "#EDF2FF", dark: "#1A224C" },
      blue4: { light: "#E0E9FF", dark: "#202B67" },
      blue5: { light: "#D1DEFF", dark: "#29357A" },
      blue6: { light: "#BFCFFF", dark: "#32408B" },
      blue7: { light: "#A9BCFF", dark: "#3B4C9F" },
      blue8: { light: "#8BA1FB", dark: "#4659BA" },
      blue9: { light: "#5669FF", dark: "#617BFF" },
      blue10: { light: "#4D5FE4", dark: "#566EF1" },
      blue11: { light: "#4452D6", dark: "#97B1FF" },
      blue12: { light: "#212A63", dark: "#D6E1FF" },
      // Lilac
      lilac1: { light: "#FCFCFF", dark: "#0F1116" },
      lilac2: { light: "#F0F4FF", dark: "#273651" },
      lilac3: { light: "#EEF0FD", dark: "#202636" },
      lilac4: { light: "#E4E8FC", dark: "#283148" },
      lilac5: { light: "#DADEF9", dark: "#323D57" },
      lilac6: { light: "#CED4F4", dark: "#3E4966" },
      lilac7: { light: "#BEC5EE", dark: "#4C5878" },
      lilac8: { light: "#A6AFE5", dark: "#5C6B91" },
      lilac9: { light: "#5E659A", dark: "#899DD0" },
      lilac10: { light: "#51578B", dark: "#7E91C4" },
      lilac11: { light: "#5B6297", dark: "#A7B7E0" },
      lilac12: { light: "#252944", dark: "#DAE1F3" },
      // Neutrals
      neutral1: { light: "#FFFFFF", dark: "#060809" },
      neutral2: { light: "#F7F7F7", dark: "#151819" },
      neutral3: { light: "#EFF0F1", dark: "#1E2224" },
      neutral4: { light: "#E7E8E9", dark: "#252A2C" },
      neutral5: { light: "#E0E1E2", dark: "#2D3133" },
      neutral6: { light: "#D8D9DA", dark: "#363B3D" },
      neutral7: { light: "#CDCECF", dark: "#44494B" },
      neutral8: { light: "#BABBBC", dark: "#5C6164" },
      neutral9: { light: "#898C8E", dark: "#696E70" },
      neutral10: { light: "#7F8283", dark: "#989EA0" },
      neutral11: { light: "#7F8283", dark: "#B5BBBD" },
      neutral12: { light: "#353839", dark: "#F2F5F7" },
      // Hover States
      transparentHover: { light: "#44475B0F", dark: "#44475B0F" },
      accentHover: { light: "#04AD83", dark: "#04AD83" },
      accentSubtleHover: { light: "#DDF5EE", dark: "#DDF5EE" },
      transparentAccentHover: { light: "#00B3860F", dark: "#00B3860F" },
      positiveHover: { light: "#04AD83", dark: "#04AD83" },
      positiveSubtleHover: { light: "#DDF5EE", dark: "#DDF5EE" },
      transparentPositiveHover: { light: "#00B3860F", dark: "#00B3860F" },
      negativeHover: { light: "#E15A3E", dark: "#E15A3E" },
      negativeSubtleHover: { light: "#F9E0DB", dark: "#F9E0DB" },
      transparentNegativeHover: { light: "#EB5B3C0F", dark: "#EB5B3C0F" },
      // Selected States
      transparentSelected: { light: "#44475B0F", dark: "#44475B0F" },
      accentSelected: { light: "#04AD83", dark: "#04AD83" },
      accentSubtleSelected: { light: "#DDF5EE", dark: "#DDF5EE" },
      transparentAccentSelected: { light: "#00B3860F", dark: "#00B3860F" },
      positiveSelected: { light: "#04AD83", dark: "#04AD83" },
      positiveSubtleSelected: { light: "#DDF5EE", dark: "#DDF5EE" },
      transparentPositiveSelected: { light: "#00B3860F", dark: "#00B3860F" },
      negativeSelected: { light: "#E15A3E", dark: "#E15A3E" },
      negativeSubtleSelected: { light: "#F9E0DB", dark: "#F9E0DB" },
      transparentNegativeSelected: { light: "#EB5B3C0F", dark: "#EB5B3C0F" },
    },
  },
  "data-viz": {
    colors: {
      dataVizLilac: { light: "#7A7AC6", dark: "#7A7AC6" },
      dataVizLilacSubtle: { light: "#DFE0EF", dark: "#1D1E2F" },
      dataVizBlue: { light: "#5669FF", dark: "#5669FF" },
      dataVizBlueSubtle: { light: "#CAD1FE", dark: "#1E2553" },
      dataVizSkyBlue: { light: "#4DA4DD", dark: "#4DA4DD" },
      dataVizSkyBlueSubtle: { light: "#C7E2F3", dark: "#1B3749" },
      dataVizMintGreen: { light: "#04B488", dark: "#04B488" },
      dataVizMintGreenSubtle: { light: "#B2E7DA", dark: "#053C2F" },
      dataVizOliveGreen: { light: "#A1B55C", dark: "#A1B55C" },
      dataVizOliveGreenSubtle: { light: "#E1E7CD", dark: "#353C22" },
      dataVizYellow: { light: "#FCCE00", dark: "#FCCE00" },
      dataVizYellowSubtle: { light: "#FCEFB1", dark: "#504306" },
      dataVizOrange: { light: "#F59817", dark: "#F59817" },
      dataVizOrangeSubtle: { light: "#FADFB8", dark: "#4E330D" },
      dataVizRed: { light: "#FF5E3B", dark: "#FF5E3B" },
      dataVizRedSubtle: { light: "#F8CBC0", dark: "#512218" },
      dataVizMagenta: { light: "#C73A75", dark: "#C73A75" },
      dataVizMagentaSubtle: { light: "#ECC2D4", dark: "#401729" },
      dataVizBrown: { light: "#9D615C", dark: "#9D615C" },
      dataVizBrownSubtle: { light: "#DFCECD", dark: "#332322" },
      dataVizGrey: { light: "#808FA3", dark: "#808FA3" },
      dataVizGreySubtle: { light: "#BEC6D0", dark: "#434C56" },
    },
  },
  wealth: {
    appendToHtml: true,
    colors: {
      gold1: { light: "#FEFDFB", dark: "#090705" },
      gold2: { light: "#FEF5E3", dark: "#241F16" },
      gold3: { light: "#FEF1D6", dark: "#262117" },
      gold4: { light: "#FBE8C1", dark: "#30291B" },
      gold5: { light: "#F6DEAB", dark: "#30291B" },
      gold6: { light: "#EAD19D", dark: "#4A3D21" },
      gold7: { light: "#DBC28D", dark: "#5E4C25" },
      gold8: { light: "#CAAB68", dark: "#7A612A" },
      gold9: { light: "#C7A865", dark: "#C7A865" },
      gold10: { light: "#C09C4A", dark: "#BC9D5A" },
      gold11: { light: "#856926", dark: "#D8B875" },
      gold12: { light: "#252017", dark: "#F5E3BD" },
    },
  },
};

// Build semantic tokens using direct references to primitives
const semanticTokens = {
  "groww-primary": {
    background: {
      primary: {
        light: primitives["groww-primary"].colors.white,
        dark: primitives["groww-primary"].colors.black,
      },
      secondary: primitives["groww-primary"].colors.gray50,
      tertiary: primitives["groww-primary"].colors.gray100,
      transparent: primitives["groww-primary"].colors.overlay00,
      surfacePrimary: {
        light: primitives["groww-primary"].colors.white,
        dark: primitives["groww-primary"].colors.gray50,
      },
      surfaceSecondary: {
        light: primitives["groww-primary"].colors.gray50,
        dark: primitives["groww-primary"].colors.gray100,
      },
      inversePrimary: {
        light: primitives["groww-primary"].colors.gray900,
        dark: primitives["groww-primary"].colors.white,
      },
      overlayPrimary: primitives["groww-primary"].colors.overlay70,
      overlaySecondary: primitives["groww-primary"].colors.overlay30,
      alwaysDark: primitives["groww-primary"].colors.black,
      alwaysLight: primitives["groww-primary"].colors.white,
      accent: primitives["groww-primary"].colors.green500,
      positive: primitives["groww-primary"].colors.green500,
      negative: primitives["groww-primary"].colors.red500,
      warning: primitives["groww-primary"].colors.yellow500,
      accentSubtle: primitives["groww-primary"].colors.green100,
      positiveSubtle: primitives["groww-primary"].colors.green100,
      negativeSubtle: primitives["groww-primary"].colors.red100,
      warningSubtle: primitives["groww-primary"].colors.yellow100,
      accentSecondary: primitives["groww-primary"].colors.purple500,
      accentSecondarySubtle: primitives["groww-primary"].colors.purple100,
      onWarningSubtle: primitives["groww-primary"].colors.yellow11,
      disabled: primitives["groww-primary"].colors.neutral2,
      surfaceZ1: {
        light: primitives["groww-primary"].colors.neutral1,
        dark: primitives["groww-primary"].colors.neutral2,
      },
      surfaceZ2: {
        light: primitives["groww-primary"].colors.neutral1,
        dark: primitives["groww-primary"].colors.neutral3,
      },
      surfaceDocked: {
        light: primitives["groww-primary"].colors.neutral1,
        dark: primitives["groww-primary"].colors.neutral2,
      },

      secondaryOnSurfaceZ1: {
        light: primitives["groww-primary"].colors.neutral2,
        dark: primitives["groww-primary"].colors.neutral3,
      },
      tertiaryOnSurfaceZ1: {
        light: primitives["groww-primary"].colors.neutral3,
        dark: primitives["groww-primary"].colors.neutral4,
      },
      accentSubtleOnSurfaceZ1: primitives["groww-primary"].colors.green2,
      secondarySubtleOnSurfaceZ1: primitives["groww-primary"].colors.blue2,
      positiveSubtleOnSurfaceZ1: primitives["groww-primary"].colors.green2,
      negativeSubtleOnSurfaceZ1: primitives["groww-primary"].colors.red2,
      warningSubtleOnSurfaceZ1: primitives["groww-primary"].colors.yellow2,
      disabledOnSurfaceZ1: {
        light: primitives["groww-primary"].colors.neutral2,
        dark: primitives["groww-primary"].colors.neutral3,
      },
      secondaryOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.neutral2,
        dark: primitives["groww-primary"].colors.neutral4,
      },
      tertiaryOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.neutral3,
        dark: primitives["groww-primary"].colors.neutral5,
      },
      accentSubtleOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.green2,
        dark: primitives["groww-primary"].colors.green3,
      },
      secondarySubtleOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.blue2,
        dark: primitives["groww-primary"].colors.blue3,
      },
      positiveSubtleOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.green2,
        dark: primitives["groww-primary"].colors.green3,
      },
      negativeSubtleOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.red2,
        dark: primitives["groww-primary"].colors.red3,
      },
      warningSubtleOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.yellow2,
        dark: primitives["groww-primary"].colors.yellow3,
      },
      disabledOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.neutral2,
        dark: primitives["groww-primary"].colors.neutral4,
      },
    },
    border: {
      primary: primitives["groww-primary"].colors.gray150,
      disabled: primitives["groww-primary"].colors.gray100,
      accent: primitives["groww-primary"].colors.green500,
      positive: primitives["groww-primary"].colors.green500,
      negative: primitives["groww-primary"].colors.red500,
      neutral: {
        light: primitives["groww-primary"].colors.gray900,
        dark: primitives["groww-primary"].colors.white,
      },
      primaryOnSurfaceZ1: {
        light: primitives["groww-primary"].colors.neutral4,
        dark: primitives["groww-primary"].colors.neutral5,
      },
      disabledOnSurfaceZ1: {
        light: primitives["groww-primary"].colors.neutral3,
        dark: primitives["groww-primary"].colors.neutral5,
      },
      primaryOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.neutral4,
        dark: primitives["groww-primary"].colors.neutral6,
      },
      disabledOnSurfaceZ2: {
        light: primitives["groww-primary"].colors.neutral3,
        dark: primitives["groww-primary"].colors.neutral6,
      }
    },
    content: {
      primary: {
        light: primitives["groww-primary"].colors.gray900,
        dark: primitives["groww-primary"].colors.white,
      },
      secondary: primitives["groww-primary"].colors.gray700,
      tertiary: primitives["groww-primary"].colors.gray500,
      inversePrimary: {
        light: primitives["groww-primary"].colors.white,
        dark: primitives["groww-primary"].colors.black,
      },
      inverseSecondary: {
        light: primitives["groww-primary"].colors.gray300,
        dark: primitives["groww-primary"].colors.gray400,
      },
      disabled: {
        light: primitives["groww-primary"].colors.gray400,
        dark: primitives["groww-primary"].colors.gray500,
      },
      onColour: primitives["groww-primary"].colors.white,
      onColourInverse: {
        light: primitives["groww-primary"].colors.gray900,
        dark: primitives["groww-primary"].colors.black,
      },
      accent: primitives["groww-primary"].colors.green500,
      negative: primitives["groww-primary"].colors.red500,
      warning: primitives["groww-primary"].colors.yellow500,
      positive: primitives["groww-primary"].colors.green500,
      accentSecondary: primitives["groww-primary"].colors.purple500,
      accentSecondarySubtle: primitives["groww-primary"].colors.purple300,
      onWarningSubtle: primitives["groww-primary"].colors.yellow11,
      onAccentSubtle: primitives["groww-primary"].colors.green11,
      onAccentSecondarySubtle: primitives["groww-primary"].colors.blue11,
      onPositiveSubtle: primitives["groww-primary"].colors.green11,
      onNegativeSubtle: primitives["groww-primary"].colors.red11,
      onWarningSubtle: primitives["groww-primary"].colors.yellow11,
      onColourInverse: {
        light: primitives["groww-primary"].colors.neutral12,
        dark: primitives["groww-primary"].colors.neutral1,
      }
    },
    interactionStateHover: {
      prefix: "bg",
      transparentHover: primitives["groww-primary"].colors.transparentHover,
      accentHover: primitives["groww-primary"].colors.accentHover,
      accentSubtleHover: primitives["groww-primary"].colors.accentSubtleHover,
      transparentAccentHover: primitives["groww-primary"].colors.transparentAccentHover,
      positiveHover: primitives["groww-primary"].colors.positiveHover,
      positiveSubtleHover: primitives["groww-primary"].colors.positiveSubtleHover,
      transparentPositiveHover: primitives["groww-primary"].colors.transparentPositiveHover,
      negativeHover: primitives["groww-primary"].colors.negativeHover,
      negativeSubtleHover: primitives["groww-primary"].colors.negativeSubtleHover,
      transparentNegativeHover: primitives["groww-primary"].colors.transparentNegativeHover,
    },
    interactionStateSelected:{
      prefix: "bg",
      transparentSelected: primitives["groww-primary"].colors.transparentSelected,
      accentSelected: primitives["groww-primary"].colors.accentSelected,
      accentSubtleSelected: primitives["groww-primary"].colors.accentSubtleSelected,
      transparentAccentSelected: primitives["groww-primary"].colors.transparentAccentSelected,
      positiveSelected: primitives["groww-primary"].colors.positiveSelected,
      positiveSubtleSelected: primitives["groww-primary"].colors.positiveSubtleSelected,
      transparentPositiveSelected: primitives["groww-primary"].colors.transparentPositiveSelected,
      negativeSelected: primitives["groww-primary"].colors.negativeSelected,
      negativeSubtleSelected: primitives["groww-primary"].colors.negativeSubtleSelected,
      transparentNegativeSelected: primitives["groww-primary"].colors.transparentNegativeSelected,
    }
  },
  "data-viz": {
    background: {
      dataVizLilac: primitives["data-viz"].colors.dataVizLilac,
      dataVizLilacSubtle: primitives["data-viz"].colors.dataVizLilacSubtle,
      dataVizBlue: primitives["data-viz"].colors.dataVizBlue,
      dataVizBlueSubtle: primitives["data-viz"].colors.dataVizBlueSubtle,
      dataVizSkyBlue: primitives["data-viz"].colors.dataVizSkyBlue,
      dataVizSkyBlueSubtle: primitives["data-viz"].colors.dataVizSkyBlueSubtle,
      dataVizMintGreen: primitives["data-viz"].colors.dataVizMintGreen,
      dataVizMintGreenSubtle: primitives["data-viz"].colors.dataVizMintGreenSubtle,
      dataVizOliveGreen: primitives["data-viz"].colors.dataVizOliveGreen,
      dataVizOliveGreenSubtle: primitives["data-viz"].colors.dataVizOliveGreenSubtle,
      dataVizYellow: primitives["data-viz"].colors.dataVizYellow,
      dataVizYellowSubtle: primitives["data-viz"].colors.dataVizYellowSubtle,
      dataVizOrange: primitives["data-viz"].colors.dataVizOrange,
      dataVizOrangeSubtle: primitives["data-viz"].colors.dataVizOrangeSubtle,
      dataVizRed: primitives["data-viz"].colors.dataVizRed,
      dataVizRedSubtle: primitives["data-viz"].colors.dataVizRedSubtle,
      dataVizMagenta: primitives["data-viz"].colors.dataVizMagenta,
      dataVizMagentaSubtle: primitives["data-viz"].colors.dataVizMagentaSubtle,
      dataVizBrown: primitives["data-viz"].colors.dataVizBrown,
      dataVizBrownSubtle: primitives["data-viz"].colors.dataVizBrownSubtle,
      dataVizGrey: primitives["data-viz"].colors.dataVizGrey,
      dataVizGreySubtle: primitives["data-viz"].colors.dataVizGreySubtle,
    },
    border: {
      dataVizLilac: primitives["data-viz"].colors.dataVizLilac,
      dataVizLilacSubtle: primitives["data-viz"].colors.dataVizLilacSubtle,
      dataVizBlue: primitives["data-viz"].colors.dataVizBlue,
      dataVizBlueSubtle: primitives["data-viz"].colors.dataVizBlueSubtle,
      dataVizSkyBlue: primitives["data-viz"].colors.dataVizSkyBlue,
      dataVizSkyBlueSubtle: primitives["data-viz"].colors.dataVizSkyBlueSubtle,
      dataVizMintGreen: primitives["data-viz"].colors.dataVizMintGreen,
      dataVizMintGreenSubtle: primitives["data-viz"].colors.dataVizMintGreenSubtle,
      dataVizOliveGreen: primitives["data-viz"].colors.dataVizOliveGreen,
      dataVizOliveGreenSubtle: primitives["data-viz"].colors.dataVizOliveGreenSubtle,
      dataVizYellow: primitives["data-viz"].colors.dataVizYellow,
      dataVizYellowSubtle: primitives["data-viz"].colors.dataVizYellowSubtle,
      dataVizOrange: primitives["data-viz"].colors.dataVizOrange,
      dataVizOrangeSubtle: primitives["data-viz"].colors.dataVizOrangeSubtle,
      dataVizRed: primitives["data-viz"].colors.dataVizRed,
      dataVizRedSubtle: primitives["data-viz"].colors.dataVizRedSubtle,
      dataVizMagenta: primitives["data-viz"].colors.dataVizMagenta,
      dataVizMagentaSubtle: primitives["data-viz"].colors.dataVizMagentaSubtle,
      dataVizBrown: primitives["data-viz"].colors.dataVizBrown,
      dataVizBrownSubtle: primitives["data-viz"].colors.dataVizBrownSubtle,
      dataVizGrey: primitives["data-viz"].colors.dataVizGrey,
      dataVizGreySubtle: primitives["data-viz"].colors.dataVizGreySubtle,
    },
    content: {
      dataVizLilac: primitives["data-viz"].colors.dataVizLilac,
      dataVizLilacSubtle: primitives["data-viz"].colors.dataVizLilacSubtle,
      dataVizBlue: primitives["data-viz"].colors.dataVizBlue,
      dataVizBlueSubtle: primitives["data-viz"].colors.dataVizBlueSubtle,
      dataVizSkyBlue: primitives["data-viz"].colors.dataVizSkyBlue,
      dataVizSkyBlueSubtle: primitives["data-viz"].colors.dataVizSkyBlueSubtle,
      dataVizMintGreen: primitives["data-viz"].colors.dataVizMintGreen,
      dataVizMintGreenSubtle: primitives["data-viz"].colors.dataVizMintGreenSubtle,
      dataVizOliveGreen: primitives["data-viz"].colors.dataVizOliveGreen,
      dataVizOliveGreenSubtle: primitives["data-viz"].colors.dataVizOliveGreenSubtle,
      dataVizYellow: primitives["data-viz"].colors.dataVizYellow,
      dataVizYellowSubtle: primitives["data-viz"].colors.dataVizYellowSubtle,
      dataVizOrange: primitives["data-viz"].colors.dataVizOrange,
      dataVizOrangeSubtle: primitives["data-viz"].colors.dataVizOrangeSubtle,
      dataVizRed: primitives["data-viz"].colors.dataVizRed,
      dataVizRedSubtle: primitives["data-viz"].colors.dataVizRedSubtle,
      dataVizMagenta: primitives["data-viz"].colors.dataVizMagenta,
      dataVizMagentaSubtle: primitives["data-viz"].colors.dataVizMagentaSubtle,
      dataVizBrown: primitives["data-viz"].colors.dataVizBrown,
      dataVizBrownSubtle: primitives["data-viz"].colors.dataVizBrownSubtle,
      dataVizGrey: primitives["data-viz"].colors.dataVizGrey,
      dataVizGreySubtle: primitives["data-viz"].colors.dataVizGreySubtle,
    },
  },
  wealth: {
    appendToHtml: true,
    background: {
      accent: primitives.wealth.colors.gold9,
      accentSubtle: primitives.wealth.colors.gold2,
    },
    border: {
      accent: primitives.wealth.colors.gold9,
      accentSubtle: primitives.wealth.colors.gold2,
    },
    content: {
      accent: primitives.wealth.colors.gold9,
      accentSubtle: primitives.wealth.colors.gold2,
    },
  },
  commodities: {
    background: {
      commoditiesGh1: primitives[ "groww-primary" ].colors.green3,
      commoditiesGh2: primitives[ "groww-primary" ].colors.green4,
      commoditiesGh3: primitives[ "groww-primary" ].colors.green5,
      commoditiesGh4: primitives[ "groww-primary" ].colors.green6,
      commoditiesGh5: primitives[ "groww-primary" ].colors.green7,
      commoditiesGh6: primitives[ "groww-primary" ].colors.green8
    },
    border: {
      commoditiesGh1: primitives[ "groww-primary" ].colors.green3,
      commoditiesGh2: primitives[ "groww-primary" ].colors.green4,
      commoditiesGh3: primitives[ "groww-primary" ].colors.green5,
      commoditiesGh4: primitives[ "groww-primary" ].colors.green6,
      commoditiesGh5: primitives[ "groww-primary" ].colors.green7,
      commoditiesGh6: primitives[ "groww-primary" ].colors.green8
    },
    content: {
      commoditiesGh1: primitives[ "groww-primary" ].colors.green3,
      commoditiesGh2: primitives[ "groww-primary" ].colors.green4,
      commoditiesGh3: primitives[ "groww-primary" ].colors.green5,
      commoditiesGh4: primitives[ "groww-primary" ].colors.green6,
      commoditiesGh5: primitives[ "groww-primary" ].colors.green7,
      commoditiesGh6: primitives[ "groww-primary" ].colors.green8
    },
  }
};

// Build utility classes using direct references to semanticTokens
const utilityClasses = {
  "groww-primary": {
    background: {
      prefix: "background",
      property: "background-color",
      tokens: semanticTokens["groww-primary"].background,
      pseudo: "",
    },
    border: {
      prefix: "border",
      property: "border",
      tokens: semanticTokens["groww-primary"].border,
    },
    content: {
      prefix: "content",
      property: "color",
      tokens: semanticTokens["groww-primary"].content,
    },
    interactionStateHover: {
      prefix: "background",
      property: "background-color",
      tokens: semanticTokens["groww-primary"].interactionStateHover,
      pseudo: ":hover",
    },
    interactionStateSelected: {
      prefix: "background",
      property: "background-color",
      tokens: semanticTokens["groww-primary"].interactionStateSelected,
      pseudo: ":active",
    },
  },
  "data-viz": {
    background: {
      prefix: "background",
      property: "background-color",
      tokens: semanticTokens["data-viz"].background,
    },
    border: {
      prefix: "border",
      property: "border",
      tokens: semanticTokens["data-viz"].border,
    },
    content: {
      prefix: "color",
      property: "color",
      tokens: semanticTokens["data-viz"].content,
    },
  },
  wealth: {
    background: {
      prefix: "background",
      property: "background-color",
      tokens: semanticTokens.wealth.background,
    },
  },
  commodities: {
    background: {
      prefix: "background",
      property: "background-color",
      tokens: semanticTokens.commodities.background,
    },
    border: {
      prefix: "border",
      property: "border",
      tokens: semanticTokens.commodities.border,
    },
    content: {
      prefix: "content",
      property: "color",
      tokens: semanticTokens.commodities.content,
    },
  }
};

module.exports = {
  primitives,
  semanticTokens,
  utilityClasses,
};
